const fs = require('fs');

const generateEmojis = () => {
  const saveDir = `./src/xml`
  const svgDir = `./assets/svgs/`;

  let emojiIndexOutput = `/**
 * Generated by scripts/generate-emojis.js
 * DO NOT EDIT!
 */

`;

let emojiMap = {};

let emojiStoryOutput = `/**
 * Generated by scripts/generate-emojis.js
 * DO NOT EDIT!
 */

import { storiesOf } from '@storybook/react-native';
import { Story, UseCase } from '@taimoormk/react-native-commons-collection/views';
import React, { ReactElement } from 'react';
import { EmojiWrapper, StyledScrollView, StyledView, TextWrapper } from './styled';
import { Emoji } from '../src/emoji';

storiesOf('Emoji', module)
  `;

  // Read root Svg emoji directory
  fs.readdirSync(svgDir).forEach(fileName => {
    if (fileName === '.DS_Store') return;

    // globalFileNames.push(fileName);
    emojiMap[fileName] = {};
    const subDir = `${svgDir}${fileName}`;

let emojiListOutput = `/**
 * Generated by scripts/generate-emojis.js
 * DO NOT EDIT!
 */

`;
    // Read sub-directory
    return fs.readdirSync(subDir).forEach(subDirFileName => {
      // trim qoutes & .svg off subDirFileName
      let trimmedStr = subDirFileName.replace(/(.svg)|-/g, '');
      let svgContent = fs.readFileSync(`${subDir}/${subDirFileName}`, 'utf8');
      emojiListOutput += `export const ${trimmedStr} = () : string => \`${svgContent}\`;
  `;

    emojiMap[fileName][trimmedStr] = () => `<EmojiWrapper>
              <Emoji emoji="${trimmedStr}" />
                <TextWrapper>
                  ${trimmedStr}
                </TextWrapper>
              </EmojiWrapper>`;

    emojiIndexOutput += `export { ${trimmedStr} } from './${fileName}'
  `;
    
    fs.writeFileSync(`${saveDir}/${fileName}.ts`, emojiListOutput);
    fs.writeFileSync(`${saveDir}/index.ts`, emojiIndexOutput);
    });
  });
  Object.keys(emojiMap).map(category => {
    emojiStoryOutput += `.add('${category}', () : ReactElement => (
    <Story>
      <UseCase
        text="Emoji => ${category}"
      >
        <StyledScrollView>
          <StyledView>
            ${Object.values(emojiMap[category]).map(value => value()).join('')}
          </StyledView>
        </StyledScrollView>
      </UseCase>
    </Story>
  ))
`;
  });
  fs.writeFileSync(`./__stories__/emoji.story.tsx`, emojiStoryOutput);
};

generateEmojis();
